blank_issues_enabled: false
issue_templates:
  - name: â“ ì§ˆë¬¸í•˜ê¸°
    description: ê¶ê¸ˆí•œ ì ì´ë‚˜ ì• ë§¤í•œ ìƒí™©ì´ ìˆë‹¤ë©´ ì´ìŠˆë¡œ ë‚¨ê²¨ì£¼ì„¸ìš”.
    labels: [question]
    template: question.yml

  - name: ğŸ’¡ ê±´ì˜ì‚¬í•­ ì œì¶œ
    description: ê·œì¹™, ì¼ì •, ìš´ì˜ ë°©ì‹ ë“±ì— ëŒ€í•œ ì œì•ˆì´ ìˆë‹¤ë©´ ë‚¨ê²¨ì£¼ì„¸ìš”.
    labels: [suggestion]
    template: suggestion.yml
